PROGRAM_spu = knn_spu
LIBRARY_embed = lib_knn_spu.a

INCLUDE = -I ../include/
CC_OPT_LEVEL = -g3

ifdef CELL_TOP
	include $(CELL_TOP)/buildutils/make.footer
else
	include /opt/cell/sdk/buildutils/make.footer
endif
